# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: focus.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66ocus.proto\x12\x05\x64warf\"F\n\x12ReqNormalAutoFocus\x12\x0c\n\x04mode\x18\x01 \x01(\r\x12\x10\n\x08\x63\x65nter_x\x18\x02 \x01(\r\x12\x10\n\x08\x63\x65nter_y\x18\x03 \x01(\r\"!\n\x11ReqAstroAutoFocus\x12\x0c\n\x04mode\x18\x01 \x01(\r\"-\n\x18ReqManualSingleStepFocus\x12\x11\n\tdirection\x18\x01 \x01(\r\"/\n\x1aReqStartManualContinuFocus\x12\x11\n\tdirection\x18\x01 \x01(\r\"\x1b\n\x19ReqStopManualContinuFocus\"\x17\n\x15ReqStopAstroAutoFocusb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'focus_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQNORMALAUTOFOCUS._serialized_start=22
  _REQNORMALAUTOFOCUS._serialized_end=92
  _REQASTROAUTOFOCUS._serialized_start=94
  _REQASTROAUTOFOCUS._serialized_end=127
  _REQMANUALSINGLESTEPFOCUS._serialized_start=129
  _REQMANUALSINGLESTEPFOCUS._serialized_end=174
  _REQSTARTMANUALCONTINUFOCUS._serialized_start=176
  _REQSTARTMANUALCONTINUFOCUS._serialized_end=223
  _REQSTOPMANUALCONTINUFOCUS._serialized_start=225
  _REQSTOPMANUALCONTINUFOCUS._serialized_end=252
  _REQSTOPASTROAUTOFOCUS._serialized_start=254
  _REQSTOPASTROAUTOFOCUS._serialized_end=277
# @@protoc_insertion_point(module_scope)
