# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motor.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmotor.proto\x12\x05\x64warf\"l\n\x0bReqMotorRun\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05speed\x18\x02 \x01(\x01\x12\x11\n\tdirection\x18\x03 \x01(\x08\x12\x15\n\rspeed_ramping\x18\x04 \x01(\x05\x12\x18\n\x10resolution_level\x18\x05 \x01(\x05\"$\n\x08ResMotor\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\"\x1a\n\x0cReqMotorStop\x12\n\n\x02id\x18\x01 \x01(\x05\"U\n\x17ReqMotorServiceJoystick\x12\x14\n\x0cvector_angle\x18\x01 \x01(\x01\x12\x15\n\rvector_length\x18\x02 \x01(\x01\x12\r\n\x05speed\x18\x03 \x01(\x01\"_\n!ReqMotorServiceJoystickFixedAngle\x12\x14\n\x0cvector_angle\x18\x01 \x01(\x01\x12\x15\n\rvector_length\x18\x02 \x01(\x01\x12\r\n\x05speed\x18\x03 \x01(\x01\"\x1d\n\x1bReqMotorServiceJoystickStop\",\n\x14ReqDualCameraLinkage\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'motor_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQMOTORRUN._serialized_start=22
  _REQMOTORRUN._serialized_end=130
  _RESMOTOR._serialized_start=132
  _RESMOTOR._serialized_end=168
  _REQMOTORSTOP._serialized_start=170
  _REQMOTORSTOP._serialized_end=196
  _REQMOTORSERVICEJOYSTICK._serialized_start=198
  _REQMOTORSERVICEJOYSTICK._serialized_end=283
  _REQMOTORSERVICEJOYSTICKFIXEDANGLE._serialized_start=285
  _REQMOTORSERVICEJOYSTICKFIXEDANGLE._serialized_end=380
  _REQMOTORSERVICEJOYSTICKSTOP._serialized_start=382
  _REQMOTORSERVICEJOYSTICKSTOP._serialized_end=411
  _REQDUALCAMERALINKAGE._serialized_start=413
  _REQDUALCAMERALINKAGE._serialized_end=457
# @@protoc_insertion_point(module_scope)
