# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63\x61mera.proto\x12\x05\x64warf\":\n\rReqOpenCamera\x12\x0f\n\x07\x62inning\x18\x01 \x01(\x08\x12\x18\n\x10rtsp_encode_type\x18\x02 \x01(\x05\"\n\n\x08ReqPhoto\"\x19\n\x08ReqBurst\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\"\x10\n\x0eReqStartRecord\"\x0f\n\rReqStopRecord\"\x9b\x02\n\x0fReqSetAllParams\x12\x10\n\x08\x65xp_mode\x18\x01 \x01(\x05\x12\x11\n\texp_index\x18\x02 \x01(\x05\x12\x11\n\tgain_mode\x18\x03 \x01(\x05\x12\x12\n\ngain_index\x18\x04 \x01(\x05\x12\x13\n\x0bircut_value\x18\x05 \x01(\x05\x12\x0f\n\x07wb_mode\x18\x06 \x01(\x05\x12\x15\n\rwb_index_type\x18\x07 \x01(\x05\x12\x10\n\x08wb_index\x18\x08 \x01(\x05\x12\x12\n\nbrightness\x18\t \x01(\x05\x12\x10\n\x08\x63ontrast\x18\n \x01(\x05\x12\x0b\n\x03hue\x18\x0b \x01(\x05\x12\x12\n\nsaturation\x18\x0c \x01(\x05\x12\x11\n\tsharpness\x18\r \x01(\x05\x12\x13\n\x0bjpg_quality\x18\x0e \x01(\x05\"\x11\n\x0fReqGetAllParams\"\xa9\x02\n\x0fResGetAllParams\x12\x10\n\x08\x65xp_mode\x18\x01 \x01(\x05\x12\x11\n\texp_index\x18\x02 \x01(\x05\x12\x11\n\tgain_mode\x18\x03 \x01(\x05\x12\x12\n\ngain_index\x18\x04 \x01(\x05\x12\x13\n\x0bircut_value\x18\x05 \x01(\x05\x12\x0f\n\x07wb_mode\x18\x06 \x01(\x05\x12\x15\n\rwb_index_type\x18\x07 \x01(\x05\x12\x10\n\x08wb_index\x18\x08 \x01(\x05\x12\x12\n\nbrightness\x18\t \x01(\x05\x12\x10\n\x08\x63ontrast\x18\n \x01(\x05\x12\x0b\n\x03hue\x18\x0b \x01(\x05\x12\x12\n\nsaturation\x18\x0c \x01(\x05\x12\x11\n\tsharpness\x18\r \x01(\x05\x12\x13\n\x0bjpg_quality\x18\x0e \x01(\x05\x12\x0c\n\x04\x63ode\x18\x0f \x01(\x05\"9\n\x16ReqStartTimelapsePhoto\x12\x10\n\x08interval\x18\x01 \x01(\x05\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"4\n\x15ResSystemWorkingState\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05state\x18\x02 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'camera_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQOPENCAMERA._serialized_start=23
  _REQOPENCAMERA._serialized_end=81
  _REQPHOTO._serialized_start=83
  _REQPHOTO._serialized_end=93
  _REQBURST._serialized_start=95
  _REQBURST._serialized_end=120
  _REQSTARTRECORD._serialized_start=122
  _REQSTARTRECORD._serialized_end=138
  _REQSTOPRECORD._serialized_start=140
  _REQSTOPRECORD._serialized_end=155
  _REQSETALLPARAMS._serialized_start=158
  _REQSETALLPARAMS._serialized_end=441
  _REQGETALLPARAMS._serialized_start=443
  _REQGETALLPARAMS._serialized_end=460
  _RESGETALLPARAMS._serialized_start=463
  _RESGETALLPARAMS._serialized_end=760
  _REQSTARTTIMELAPSEPHOTO._serialized_start=762
  _REQSTARTTIMELAPSEPHOTO._serialized_end=819
  _RESSYSTEMWORKINGSTATE._serialized_start=821
  _RESSYSTEMWORKINGSTATE._serialized_end=873
# @@protoc_insertion_point(module_scope)
