# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csystem.proto\x12\x05\x64warf\"\x1f\n\nReqSetTime\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\"\"\n\x0eReqSetTimezone\x12\x10\n\x08timezone\x18\x01 \x01(\t\"\x1d\n\rReqSetMtpMode\x12\x0c\n\x04mode\x18\x01 \x01(\x05\"\x1d\n\rReqSetCpuMode\x12\x0c\n\x04mode\x18\x01 \x01(\x05\" \n\x10ReqsetMasterLock\x12\x0c\n\x04lock\x18\x01 \x01(\x08\"\x0c\n\nReqOpenRgb\"\r\n\x0bReqCloseRgb\"\x11\n\x0fReqOpenPowerInd\"\x12\n\x10ReqClosePowerInd\"\x0e\n\x0cReqPowerDown\"\x0b\n\tReqRebootb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQSETTIME._serialized_start=23
  _REQSETTIME._serialized_end=54
  _REQSETTIMEZONE._serialized_start=56
  _REQSETTIMEZONE._serialized_end=90
  _REQSETMTPMODE._serialized_start=92
  _REQSETMTPMODE._serialized_end=121
  _REQSETCPUMODE._serialized_start=123
  _REQSETCPUMODE._serialized_end=152
  _REQSETMASTERLOCK._serialized_start=154
  _REQSETMASTERLOCK._serialized_end=186
  _REQOPENRGB._serialized_start=188
  _REQOPENRGB._serialized_end=200
  _REQCLOSERGB._serialized_start=202
  _REQCLOSERGB._serialized_end=215
  _REQOPENPOWERIND._serialized_start=217
  _REQOPENPOWERIND._serialized_end=234
  _REQCLOSEPOWERIND._serialized_start=236
  _REQCLOSEPOWERIND._serialized_end=254
  _REQPOWERDOWN._serialized_start=256
  _REQPOWERDOWN._serialized_end=270
  _REQREBOOT._serialized_start=272
  _REQREBOOT._serialized_end=283
# @@protoc_insertion_point(module_scope)
